### ISSUE TITLE
Plugin request: S3

### ISSUE THREAD

**Issue by timgl** [PostHog/plugin-repository#12]
I want to dump all my persons and events into an s3 bucket for analysis/backup

**Comment by mariusandra** [comment]
Thinking out loud on how to make this.

I assume at the end of the day we'd be happy with a long `YYYMMDD-HHMM-DIGEST.csvjson` file, that contains a bunch of collected events? One event json per line `{ event: '', properties: {} }`.

To make that happen, we need to either:

1) Have a periodic task (`runEveryMinute`), that calls the [PostHog Events API](https://posthog.com/docs/api/events), to get all events from `$lastrun` (could be a huge number?) and then creates one or more `.csvjson` or `.txt` files that it uploads to S3. This script could be set to run from `$first_event` to back up all ingested events to S3.

2) Alternatively, every time an event is run through the S3 plugin, store it in a list in Redis. Then have a `runEveryMinute` task that reads the entire list from redis and sends it to S3.

Which seems like a better approach?

**Comment by mariusandra** [comment]
Also, this probably requires us to add and export a few extra vendor libraries to talk to S3 via the AWS SDK. Segment [exposes](https://segment.com/docs/connections/functions/destination-functions/#runtime-and-dependencies) the entire `aws-sdk` package just as `AWS`.

**Comment by mariusandra** [comment]
And it's done! 🎉 

https://github.com/PostHog/s3-export-plugin

**Comment by mariusandra** [comment]
I'll add it to the repo once 1.24 is out.
