### ISSUE TITLE
Plugin request: Snowflake

### ISSUE THREAD

**Issue by timgl** [PostHog/plugin-repository#13]
I want to dump all my events and person information in Snowflake.

~I've actually had a look at this. it seems the only way to do this is to create .csv's of events, upload them to s3 and then make a call to snowflake to ingest that. I'm trying to get a direct contact there to ask if there's an easier way, and to get added to their PartnerConnect program.~

I think the easiest way to do this is to use their [node connector](https://github.com/snowflakedb/snowflake-connector-nodejs), then do something [like this](https://github.com/airbytehq/airbyte/blob/0faec824dc3279a0ca8aa32490e13ec50ac219d8/airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeSqlOperations.java#L45) to insert it one at a time.

**Comment by mariusandra** [comment]
Depends on https://github.com/PostHog/plugin-repository/issues/12 then

**Comment by jamesefhawkins** [comment]
I've had no response from the contact I got referred to, I've a third person I've been told I can get connected to through an investor (support = world networking championships, clearly), have asked him to intro!

**Comment by mariusandra** [comment]
This is built: https://github.com/PostHog/snowflake-export-plugin

![image](https://user-images.githubusercontent.com/53387/112825443-0645f000-908c-11eb-8d38-0fb3d66c45f6.png)

![image](https://user-images.githubusercontent.com/53387/112825512-1eb60a80-908c-11eb-9aa2-5db30f05a5c6.png)

Some points:
- The following needs to be merged for it to work: https://github.com/PostHog/plugin-server/pull/291
- Snowflake supports a few different methods of authentication. Currently only "password" is implemented. Adding the "private key" option shouldn't be that much extra work.
- Finally, we have the same case as with the bigquery export: there's no retry support with this plugin. In case snowflake or your network is down at some point, the events are lost. Good enough for now, but we need to find a universal solution to it (see https://github.com/PostHog/plugin-server/issues/273)

**Comment by timgl** [comment]
I think we can safely ignore $snapshot and $feature_flag_called events for now (and maybe even autocapture). Other than that great work!

**Comment by mariusandra** [comment]
I can add some option in the plugin config to select what types of events to send. Who knows, someone might actually want to send their `$snapshot`s somewhere for archival. The BigQuery plugin theoretically suffers from the same situation as it also just sends everything.

**Comment by mariusandra** [comment]
I added this (default values in screenshot):

![image](https://user-images.githubusercontent.com/53387/112827155-4017f600-908e-11eb-928f-68e0bbc26bdf.png)

**Comment by timgl** [comment]
yeah i think that's fine for now. would be nice to standardise that somehow but not urgent

**Comment by Twixes** [comment]
Snowflake contact woes aside, I would say this can be considered done #18
