### ISSUE TITLE
New repo name proposal: plugin-directory

### ISSUE THREAD

**Issue by Twixes** [PostHog/plugin-repository#2]
The current name is confusing as there also exists [posthog-plugins](https://github.com/PostHog/posthog-plugins) and because it may imply that this repo contains actual plugins – while in reality it's just a central directory linking to PostHog-verified plugins. The name should reflect the spirit.
Feedback needed and welcome.

**Comment by mariusandra** [comment]
If we would rename it, I'd go for `plugin-repository`, just to be really clear of the contents. "Repository" IMHO is a more accurate and more commonly used (e.g. more recognisable) label than "directory".

That said, the way we distribute plugins is a bit in flux (how to integrate with https://github.com/PostHog/plugin-snippets ?), so I'd let this sit for another week or so.
